void uint2str(unsigned char *buf, unsigned int val);
void uchar2str(unsigned char *buf, unsigned char val);
void uchar2xstr(unsigned char *buf, unsigned char val);
unsigned char str2uchar(unsigned char *buf);
unsigned char xstr2uchar(unsigned char *buf);
unsigned long int astr2luint(unsigned char *buf);
void uint2xstr(unsigned char *buf, unsigned int val);
unsigned char bcd2bin(unsigned char bcd);
unsigned char bin2bcd(unsigned char bin);
unsigned long int astr2luint(unsigned char *buf);
void luint2str(unsigned char *buf, unsigned long int val);
void luint2xstr(unsigned char*buf, unsigned long int val);
void autocalibrate(void);
unsigned int getkhz(unsigned char i);
